### ISSUE TITLE
插件有线程安全问题

### ISSUE THREAD

**Issue by flipped0119** [Link-Kou/intellij-mybaitslog#129]
启用插件，在openSession()的时候，有可能触发
Error opening session. Cause: java.util.ConcurrentModificationException### Error opening session.  Cause: java.util.ConcurrentModificationException
### Cause: java.util.ConcurrentModificationException
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:100)
at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:47)

**Comment by flipped0119** [comment]
初步定位到是org.apache.ibatis.plugin.InterceptorChain.interceptors这个List中一边添加LogInterceptor一边openSession导致的
