### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal group reference

### ISSUE THREAD

**Issue by sunxk123** [Link-Kou/intellij-mybaitslog#137]
![D96D69BD-4074-4338-A6E2-5B7A097810C1](https://github.com/Link-Kou/intellij-mybaitslog/assets/19604551/a322045f-0818-4471-baa2-a15fed2be8f5)

at com.linkkou.mybatis.log.LogInterceptor.replaceFirst(LogInterceptor.java:152)at com.linkkou.mybatis.log.LogInterceptor.getCompleteSql(LogInterceptor.java:123)at com.linkkou.mybatis.log.LogInterceptor.intercept(LogInterceptor.java:78)

**Comment by sunxk123** [comment]
idea版本：2023.2.2
mybatis log版本：5.0.8.2

**Comment by liguochuan00** [comment]
遇到同样的问题
