### ISSUE TITLE
com.linkkou.mybatis.log.LogInterceptor.replaceFirst中使用String.replaceFirst字符串含特殊字符$会报错java.lang.IllegalArgumentException: Illegal group reference

### ISSUE THREAD

**Issue by li1135759862** [Link-Kou/intellij-mybaitslog#142]
java.lang.IllegalArgumentException: Illegal group reference
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
	at java.base/java.util.regex.Matcher.replaceFirst(Matcher.java:1407)
	at java.base/java.lang.String.replaceFirst(String.java:2895)
	at com.linkkou.mybatis.log.LogInterceptor.replaceFirst(LogInterceptor.java:152)
	at com.linkkou.mybatis.log.LogInterceptor.getCompleteSql(LogInterceptor.java:123)
	at com.linkkou.mybatis.log.LogInterceptor.intercept(LogInterceptor.java:78)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy78.update(Unknown Source)

**Comment by fenghlkevin** [comment]
我发现只要是程序报错就会有这个错误
