### ISSUE TITLE
无法打开Terminal窗口

### ISSUE THREAD

**Issue by hobbyWang** [Link-Kou/intellij-mybaitslog#2]
Caught exception in terminal thread

java.lang.RuntimeException: Error while applying com.plugins.mybaitslog.filter.MyBatisLogFilter@5a5d7c00 to ''
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:82)
	at com.intellij.terminal.JBTerminalWidget.lambda$runFilters$1(JBTerminalWidget.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.terminal.JBTerminalWidget.runFilters(JBTerminalWidget.java:85)
	at com.intellij.terminal.JBTerminalWidget.lambda$new$0(JBTerminalWidget.java:78)
	at com.jediterm.terminal.model.hyperlinks.TextProcessing.doProcessHyperlinks(TextProcessing.java:64)
	at com.jediterm.terminal.model.hyperlinks.TextProcessing.processHyperlinks(TextProcessing.java:42)
	at com.jediterm.terminal.model.TerminalTextBuffer.eraseCharacters(TerminalTextBuffer.java:427)
	at com.jediterm.terminal.model.JediTerminal.eraseInLine(JediTerminal.java:392)
	at com.jediterm.terminal.emulator.JediEmulator.eraseInLine(JediEmulator.java:738)
	at com.jediterm.terminal.emulator.JediEmulator.processControlSequence(JediEmulator.java:379)
	at com.jediterm.terminal.emulator.JediEmulator.processEscapeSequence(JediEmulator.java:104)
	at com.jediterm.terminal.emulator.JediEmulator.processChar(JediEmulator.java:78)
	at com.jediterm.terminal.DataStreamIteratingEmulator.next(DataStreamIteratingEmulator.java:36)
	at com.jediterm.terminal.TerminalStarter.start(TerminalStarter.java:54)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:361)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.String.contains(String.java:2036)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.prints(MyBatisLogFilter.java:50)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:36)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:76)
	... 17 more

**Comment by Link-Kou** [comment]
@hobbyWang  你用的IDEA是什么版本的？

**Comment by hobbyWang** [comment]
2020.1

**Comment by Link-Kou** [comment]
@hobbyWang   我自己这里是好的，如果不行你就重新下载安装一下插件。还有就是我编译的时候是基于商业版本编译的。对于社区版是否支持我没有测试。

**Comment by Link-Kou** [comment]
@hobbyWang  有情况下会出现空指针，是获取不到控制台的数据。我后面会出现打包一下。
