### ISSUE TITLE
提个小问题

### ISSUE THREAD

**Issue by AprilViolet** [Link-Kou/intellij-mybaitslog#3]
该版本的插件会Grep Console插件有冲突，导致Grep Console插件没有效果，不知算不算这里的bug，之前使用老版本的时候是不会的。

版本:IDEA2020.1.1

**Comment by Link-Kou** [comment]
@AprilViolet  我一会下载你说的插件，调试一下看看情况

**Comment by AprilViolet** [comment]
@Link-Kou 好的，感谢，Grep Console是可以过滤打印日志、自定义不同日志颜色的插件，所以估计是和这个冲突了。

**Comment by Link-Kou** [comment]
@AprilViolet  请问你的 Grep Console 配置了什么内容吗？

![image](https://user-images.githubusercontent.com/22113151/82635478-d8ee1180-9c32-11ea-942f-dc2b5e50bf3d.png)

我这里测试没有什么问题

**Comment by AprilViolet** [comment]
@Link-Kou 啊，为啥我这边的有问题啊QAQ，难道是我设置了什么，我看看

**Comment by AprilViolet** [comment]
@Link-Kou 不知道是不是我这里的插件乱套了，我开启mybaitslog插件，Grep Console插件就不起作用了，Grep Console配置的颜色都没有了。而且mybaitslog报了一个错误

```
java.lang.RuntimeException: Error while applying com.plugins.mybaitslog.filter.MyBatisLogFilter@d6b6998 to '"D:\SoftwareInstallation\LearnSoftware\JAVA\Oracle JDK11\bin\java.exe" -agentlib:jdwp=transport=dt_shmem,address=javadebug,suspend=y,server=n -Dvisualvm.id=195718238253200 -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:D:\SoftwareInstallation\LearnSoftware\apps\IDEA-U\ch-0\201.7223.91\plugins\java\lib\rt\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "F:\800 - Transfer&中转站\810 - Learning&学习相关\811 - Program&编程相关\IDEAJava\springboot-shiro\target\classes;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-thymeleaf\2.2.5.RELEASE\spring-boot-starter-thymeleaf-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter\2.2.5.RELEASE\spring-boot-starter-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-logging\2.2.5.RELEASE\spring-boot-starter-logging-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\logging\log4j\log4j-to-slf4j\2.12.1\log4j-to-slf4j-2.12.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\logging\log4j\log4j-api\2.12.1\log4j-api-2.12.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\slf4j\jul-to-slf4j\1.7.30\jul-to-slf4j-1.7.30.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\yaml\snakeyaml\1.25\snakeyaml-1.25.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\thymeleaf\thymeleaf-spring5\3.0.11.RELEASE\thymeleaf-spring5-3.0.11.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\thymeleaf\thymeleaf\3.0.11.RELEASE\thymeleaf-3.0.11.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\attoparser\attoparser\2.0.5.RELEASE\attoparser-2.0.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\unbescape\unbescape\1.1.6.RELEASE\unbescape-1.1.6.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\thymeleaf\extras\thymeleaf-extras-java8time\3.0.4.RELEASE\thymeleaf-extras-java8time-3.0.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-web\2.2.5.RELEASE\spring-boot-starter-web-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-json\2.2.5.RELEASE\spring-boot-starter-json-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\core\jackson-databind\2.10.2\jackson-databind-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\core\jackson-annotations\2.10.2\jackson-annotations-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\core\jackson-core\2.10.2\jackson-core-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.10.2\jackson-datatype-jdk8-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.10.2\jackson-datatype-jsr310-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.10.2\jackson-module-parameter-names-2.10.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-tomcat\2.2.5.RELEASE\spring-boot-starter-tomcat-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.31\tomcat-embed-core-9.0.31.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.31\tomcat-embed-el-9.0.31.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.31\tomcat-embed-websocket-9.0.31.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-validation\2.2.5.RELEASE\spring-boot-starter-validation-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\hibernate\validator\hibernate-validator\6.0.18.Final\hibernate-validator-6.0.18.Final.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-web\5.2.4.RELEASE\spring-web-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-beans\5.2.4.RELEASE\spring-beans-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-webmvc\5.2.4.RELEASE\spring-webmvc-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-aop\5.2.4.RELEASE\spring-aop-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-context\5.2.4.RELEASE\spring-context-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-expression\5.2.4.RELEASE\spring-expression-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-data-jpa\2.2.5.RELEASE\spring-boot-starter-data-jpa-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-aop\2.2.5.RELEASE\spring-boot-starter-aop-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\aspectj\aspectjweaver\1.9.5\aspectjweaver-1.9.5.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-starter-jdbc\2.2.5.RELEASE\spring-boot-starter-jdbc-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\zaxxer\HikariCP\3.4.2\HikariCP-3.4.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-jdbc\5.2.4.RELEASE\spring-jdbc-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\activation\jakarta.activation-api\1.2.2\jakarta.activation-api-1.2.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\persistence\jakarta.persistence-api\2.2.3\jakarta.persistence-api-2.2.3.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta.transaction-api-1.3.3.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\hibernate\hibernate-core\5.4.12.Final\hibernate-core-5.4.12.Final.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\jboss\logging\jboss-logging\3.4.1.Final\jboss-logging-3.4.1.Final.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\javassist\javassist\3.24.0-GA\javassist-3.24.0-GA.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\net\bytebuddy\byte-buddy\1.10.8\byte-buddy-1.10.8.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\jboss\jandex\2.1.1.Final\jandex-2.1.1.Final.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\dom4j\dom4j\2.1.1\dom4j-2.1.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\hibernate\common\hibernate-commons-annotations\5.1.0.Final\hibernate-commons-annotations-5.1.0.Final.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\glassfish\jaxb\jaxb-runtime\2.3.2\jaxb-runtime-2.3.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\glassfish\jaxb\txw2\2.3.2\txw2-2.3.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\sun\istack\istack-commons-runtime\3.0.8\istack-commons-runtime-3.0.8.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\jvnet\staxex\stax-ex\1.8.1\stax-ex-1.8.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\com\sun\xml\fastinfoset\FastInfoset\1.2.16\FastInfoset-1.2.16.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\data\spring-data-jpa\2.2.5.RELEASE\spring-data-jpa-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\data\spring-data-commons\2.2.5.RELEASE\spring-data-commons-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-orm\5.2.4.RELEASE\spring-orm-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-tx\5.2.4.RELEASE\spring-tx-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-aspects\5.2.4.RELEASE\spring-aspects-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-devtools\2.2.5.RELEASE\spring-boot-devtools-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot\2.2.5.RELEASE\spring-boot-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\boot\spring-boot-autoconfigure\2.2.5.RELEASE\spring-boot-autoconfigure-2.2.5.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\mysql\mysql-connector-java\8.0.19\mysql-connector-java-8.0.19.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\jakarta\xml\bind\jakarta.xml.bind-api\2.3.2\jakarta.xml.bind-api-2.3.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-core\5.2.4.RELEASE\spring-core-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\springframework\spring-jcl\5.2.4.RELEASE\spring-jcl-5.2.4.RELEASE.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-spring\1.5.1\shiro-spring-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-core\1.5.1\shiro-core-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-lang\1.5.1\shiro-lang-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-cache\1.5.1\shiro-cache-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-crypto-hash\1.5.1\shiro-crypto-hash-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-crypto-core\1.5.1\shiro-crypto-core-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-crypto-cipher\1.5.1\shiro-crypto-cipher-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-config-core\1.5.1\shiro-config-core-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-config-ogdl\1.5.1\shiro-config-ogdl-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\commons-beanutils\commons-beanutils\1.9.4\commons-beanutils-1.9.4.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-event\1.5.1\shiro-event-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\apache\shiro\shiro-web\1.5.1\shiro-web-1.5.1.jar;D:\SoftwareInstallation\LearnSoftware\Maven\Maven Repository\org\owasp\encoder\encoder\1.2.2\encoder-1.2.2.jar;D:\SoftwareInstallation\LearnSoftware\apps\IDEA-U\ch-0\201.7223.91\lib\idea_rt.jar" com.april.shiro.SpringbootShiroApplication
'
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:82)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:231)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:220)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.access$200(AsyncFilterRunner.java:188)
	at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:148)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:443)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:451)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:384)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.String.contains(String.java:2036)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.prints(MyBatisLogFilter.java:50)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:36)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:76)
	... 28 more
```

可以贴一下你Grep Console插件的配置么，实在感谢。
我这边还是来试试都卸载了看看会不好

**Comment by Link-Kou** [comment]
@AprilViolet  我对源代码中的 com.plugins.mybaitslog.filter.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:36)
做了空判断。可能会解决掉。你可以重新下载安装。1.0.2版本

https://raw.githubusercontent.com/Link-Kou/intellij-mybaitslog/master/plugin/plugin.intellij.assistant.mybaitslog-2020.1-1.0.2.jar

**Comment by AprilViolet** [comment]
@Link-Kou 
我这边测试了一下，还是会报相同的错误，版本已经更新到了1.0.2
```
Caused by: java.lang.NullPointerException
	at java.base/java.lang.String.contains(String.java:2036)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.prints(MyBatisLogFilter.java:52)
	at com.plugins.mybaitslog.filter.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:37)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:76)
	... 28 more
```
![image](https://user-images.githubusercontent.com/40155496/82641051-4a7f8d00-9c3e-11ea-8723-6aa211811179.png)

不知道是不是我这边插件装多了，倒是环境错乱了，不过应该也不至于啊，我用过原版作者的，是没有这个问题的，和Grep Console插件也兼容。

![image](https://user-images.githubusercontent.com/40155496/82641248-a77b4300-9c3e-11ea-9d79-4abcc392ef17.png)

**Comment by Link-Kou** [comment]
@AprilViolet  我找一台win的电脑测试一下。你等等。我MAC下面没有问题。我看看Win下面的情况下是怎么回事

**Comment by AprilViolet** [comment]
@Link-Kou 好吧，我是Windows的，确实没有试过MAC的。没事，等你有时间，不着急

**Comment by Link-Kou** [comment]
@AprilViolet  你在试一下 
https://raw.githubusercontent.com/Link-Kou/intellij-mybaitslog/master/plugin/plugin.intellij.assistant.mybaitslog-2020.1-1.0.3.jar

**Comment by AprilViolet** [comment]
@Link-Kou nice，欧克了，没有啥问题！👍感谢修复！
