### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.gson.GsonBuilder

### ISSUE THREAD

**Issue by zzqo** [Link-Kou/intellij-mybaitslog#86]
IDEA信息：
        IntelliJ IDEA 2023.1 (Ultimate Edition)
        内部版本号 #IU-231.8109.175，2023年3月28日 构建
        运行时版本: 17.0.6+10-b829.5 amd64
        VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.

Mybatis Log EasyPlus版本：5.0.1
错误信息：
        Creating a new SqlSession
        2023-04-04 23:02:40.878-[ERROR]-[http-nio-7336-exec-1]-[org.apache.juli.logging.DirectJDKLog:175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder] with root cause
        java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	        at com.linkkou.mybatis.log.LogInterceptor.<clinit>(LogInterceptor.java:48)
	        at com.linkkou.mybatis.log.SubInterceptorChain.<init>(SubInterceptorChain.java:25)
	        at org.apache.ibatis.plugin.InterceptorChain.pluginAll(InterceptorChain.java)
	        at org.apache.ibatis.session.Configuration.newExecutor(Configuration.java:615)
	        at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:96)
	        at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:57)
	        at org.mybatis.spring.SqlSessionUtils.getSqlSession(SqlSessionUtils.java:105)
	        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:423)
	        at com.sun.proxy.$Proxy96.selectOne(Unknown Source)
	        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
	        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
	        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	        at com.sun.proxy.$Proxy123.findUserInfo(Unknown Source)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.lang.reflect.Method.invoke(Method.java:498)
	        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	        at com.sun.proxy.$Proxy124.findUserInfo(Unknown Source)
	        at com.shendi.sealand.system.service.impl.SysUserServiceImpl.userLogin(SysUserServiceImpl.java:243)
	        at com.shendi.sealand.system.service.impl.SysUserServiceImpl$$FastClassBySpringCGLIB$$5e418165.invoke(<generated>)
	        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	        at com.shendi.sealand.system.service.impl.SysUserServiceImpl$$EnhancerBySpringCGLIB$$98176369.userLogin(<generated>)
	        at com.shendi.sealand.system.controller.LoginController.userLogin(LoginController.java:78)
	        at com.shendi.sealand.system.controller.LoginController$$FastClassBySpringCGLIB$$ca9221c0.invoke(<generated>)
	        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:120)
	        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	        at com.shendi.sealand.system.controller.LoginController$$EnhancerBySpringCGLIB$$41e2143e.userLogin(<generated>)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.lang.reflect.Method.invoke(Method.java:498)
	        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at com.shendi.sealand.common.filter.ParamsFilter.doFilter(ParamsFilter.java:45)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	        at java.lang.Thread.run(Thread.java:748)

**Comment by Link-Kou** [comment]
可以下载最新的5.0.2在试一下

**Comment by Link-Kou** [comment]
@zzqo 如果是java17  请添加
```xml
--add-opens java.base/java.lang=ALL-UNNAMED
```
下个版本优化一下java17以上的问题

**Comment by zzqo** [comment]
项目使用的是jdk8，可以使用了

**Comment by Link-Kou** [comment]
@zzqo  你哪里有SpringMVC的项目的吗？我已经好多年没有进行过SpringMVC项目的开发了。现在可能大家都是BOOT了吧。
如果你那里有可以协助测试测试吗？没有的话算了。
