### ISSUE TITLE
有时输出sql 插件会报错

### ISSUE THREAD

**Issue by smous** [Link-Kou/intellij-mybaitslog#90]
com.intellij.execution.filters.CompositeFilter$ApplyFilterException: Error while applying com.plugins.mybaitslog.integration.MyBatisLogFilter@67d54c1e to '==>  SQLStructure: {"id":"com.xxx..user.dao.LoginTokenMapper.deleteByUserId","originalSql":"delete from SYS_LOGIN_TOKEN\n        where USER_ID = #{userId}\n         \n                and DEVICE_TYPE = #{deviceType}","completeSql":"delete from SYS_LOGIN_TOKEN where USER_ID = 1726 and DEVICE_TYPE = 'pc'","parameter":"[{\"userId\":\"1726\"},{\"deviceType\":\"'pc'\"}]","total":0}
'
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:88)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:230)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:219)
	at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:147)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/ide/util/PropertiesComponent.getValue must not be null
	at com.intellij.ide.util.PropertiesComponent.$$$reportNull$$$0(PropertiesComponent.java)
	at com.intellij.ide.util.PropertiesComponent.getValue(PropertiesComponent.java)
	at com.plugins.mybaitslog.Config$Idea.getColor(Config.java:100)
	at com.plugins.mybaitslog.console.PrintlnUtil.printlnSqlType(PrintlnUtil.java:154)
	at com.plugins.mybaitslog.console.PrintlnUtil.prints(PrintlnUtil.java:82)
	at com.plugins.mybaitslog.integration.MyBatisLogFilter.applyFilter(MyBatisLogFilter.java:42)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:82)
	... 39 more

**Comment by Link-Kou** [comment]
@smous  插件是什么版本的

**Comment by smous** [comment]
> @smous 插件是什么版本的

最新版 5.0.5

**Comment by Link-Kou** [comment]
@smous  找到BUG了，感谢你。晚上发布5.0.6

**Comment by smous** [comment]
> @smous 找到BUG了，感谢你。晚上发布5.0.6

赞~

**Comment by Link-Kou** [comment]
@smous  已经修复发布
